### PR TITLE
Remove script host from smarty variables

### PR DESCRIPTION
**Pull request by withanage**
@NateWr 

master branch addition  for the  tinymce url handling as in  #123

### CODE REVIEW

**Comment by NateWr** [comment]
Can you create an issue for this at pkp-lib and link both of the PRs (stable and master) to that?

**Comment by withanage** [comment]
This  Issue  explains the issue solved in this PR
https://github.com/pkp/pkp-lib/issues/6344

**Comment by NateWr** [comment]
It looks like you'll need to rebase this against the latest `master` branch. (Also don't forget to run the linter... looks like there are some whitespace issues.)

**Comment by NateWr** [comment]
Pushed directly in https://github.com/pkp/ui-library/commit/da9b36a0d9440c930017a5ca1c2f5c429ab0c1ab

**Pull request closed without merging**
